### ISSUE TITLE
Lsp config not found on fresh install - Mac

### ISSUE THREAD

**Issue by PrinceP** [VapourNvim/VapourNvim#81]
![Screenshot 2022-05-26 at 10 04 34 AM](https://user-images.githubusercontent.com/10251537/170416677-b39c9f48-1f51-4f7f-b289-e91e22bc49ea.png)

**Comment by PrinceP** [comment]
Solved by
![Screenshot 2022-05-26 at 7 17 02 PM](https://user-images.githubusercontent.com/10251537/170500637-f2f79a37-d3ab-4f56-a4d8-575dc6d55ba7.png)

**Comment by horusbou** [comment]
hey, i still have this problem
i'm using an ubuntu 20.04
could you tell me on which file exist that line?

**Comment by PrinceP** [comment]
@horusbou Cam you use live grep to find that line

**Comment by ss77a** [comment]
112 of lua/plugins/init.lua removing the additional config seems to make things work for me
